pipeline {
    agent none
    environment { 
        DOCKER_IMAGE = 'localhost:5000/flask-docker'
        DOCKER_TAG="latest"
    }
    stages {
        stage('Build application container'){
            agent { node {label 'master'} }
            steps{
                sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                updateGitlabCommitStatus name: 'Build', state: 'success'
            }
        }
        stage('Push application container to docker registry'){
            agent { node {label 'master'} }
            steps{
                sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
                sh "docker image rm ${DOCKER_IMAGE}:${DOCKER_TAG}"
                updateGitlabCommitStatus name: 'Push', state: 'success'
            }
        }
        stage('Deploy to staging'){
            agent { node {label 'master'} }
            steps{
                sh "docker run -d -p 5050:5000 ${DOCKER_IMAGE}:${DOCKER_TAG}"
                updateGitlabCommitStatus name: 'Deploy', state: 'success'
            }
        }
    }
}

