version: "3.9"
services:
    gitlab:
        container_name: gitlab
        image: 'gitlab/gitlab-ee:latest'
        restart: always
        hostname: 'gitlab.local'
        ports:
          - '80:80'
          - '443:443'
          - '22:22'
        volumes:
          - '/var/gitlab/config:/etc/gitlab'
          - '/var/gitlab/logs:/var/log/gitlab'
          - '/var/gitlab/data:/var/opt/gitlab'
    registry:
        container_name: registry
        image: registry:2
        hostname: registry.local
        restart: always
        ports:
          - '5000:5000'
          #- '443:443'
          #- '22:22'
        volumes:
          - '/var/docker_registry:/var/lib/registry'
        