version: "3.9"
services:

    jenkins:
        container_name: jenkins
        user: 1000:999
        image: jenkins/jenkins:lts
        hostname: jenkins.local
        restart: always
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker

    gitlab:
        container_name: gitlab
        image: gitlab/gitlab-ce
        restart: always
        hostname: gitlab.local
        ports:
          - '80:80'
          - '443:443'
          - '22:22'
        volumes:
          - gitlab-config:/etc/gitlab
          - gitlab-logs:/var/log/gitlab
          - gitlab-data:/var/opt/gitlab
        environment: 
          GITLAB_OMNIBUS_CONFIG: |
            gitlab_rails['initial_root_password'] = '12341234'

    registry:
        container_name: registry
        image: registry:2.6.2
        hostname: registry.local
        restart: always
        ports:
          - '5000:5000'
        volumes:
          - registry-data:/var/lib/registry
          - ${PWD}/certs:/${PWD}/certs
        environment:
          REGISTRY_HTTP_TLS_CERTIFICATE: ${PWD}/certs/registry.local.crt
          REGISTRY_HTTP_TLS_KEY: ${PWD}/certs/registry.local.key

    sonarqube:
        container_name: sonarqube
        image: sonarqube:7.9.4-community
        hostname: sonarqube.local
        restart: always
        ports:
          - '9000:9000'
        volumes: 
          - sonarqube_conf:/opt/sonarqube/conf
          - sonarqube_data:/opt/sonarqube/data
        environment:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'

    zap:
        container_name: zap
        image: owasp/zap2docker-stable
        ports:
          - 8000:8000
        volumes: 
          - zap-reports:/zap/reports
        entrypoint: zap-x.sh -daemon -host 0.0.0.0 -port 8000 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  registry-data:
  jenkins-data:
  sonarqube_conf:
  sonarqube_data:
  zap-reports: